### ISSUE TITLE
GH-Pages: Emojis

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/cs50x-live#111] opened 2016-01-20 16:25 UTC
emojis get mangled. 

For example, see the bottom of the <a href="http://education.launchcode.org/cs50x-stlouis/helpful-resources/CS50-IDE/file-management-resource.html#folder-format" target="_blank">Folder Management</a> page

**Comment by digshake** [comment] 2016-01-21 17:55
Duplicate of #70

**Closed as completed** 2016-01-22 17:38 UTC
Labels: duplicate
